---

log:
  level: "debug"
  format: "text"
  output: "stdout"
  file: "logs/anyproxy.log"
  max_size: 100           
  max_backups: 5          
  max_age: 30             
  compress: true          

proxy:
  socks5:
    listen_addr: ":1080"
    auth_username: ""
    auth_password: ""
  http:
    listen_addr: ":8088"
    auth_username: "user"
    auth_password: "password"

transport:
  type: "websocket"

gateway:
  listen_addr: ":8443"
  tls_cert: "certs/server.crt"
  tls_key: "certs/server.key"
  auth_username: "gateway_user"
  auth_password: "gateway_password"

client:
  gateway_addr: "127.0.0.1:8443"
  gateway_tls_cert: "certs/server.crt"
  client_id: "client"
  # group_id: "example-group"
  replicas: 10
  auth_username: "gateway_user"
  auth_password: "gateway_password"
  forbidden_hosts:
    - "0.0.0.0"
    # - "127.0.0.1"  # Commented out to allow port forwarding to local services
    # - "localhost"  # Commented out to allow port forwarding to local services
    - "192.168.1.1"
    - "internal.example.com"
  allowed_hosts:
    - "example.com"
    - "example.org"
    - "example.net"
    - ".*"
  open_ports:
    - remote_port: 8000
      protocol: "tcp"
      local_port: 3000
      local_host: "127.0.0.1"
    - remote_port: 8022
      protocol: "udp"
      local_port: 22
      local_host: "192.168.1.1"